### ISSUE TITLE
Routing Errors

### ISSUE THREAD

**Issue by ajm188** [Aaronneyer/the_jolly_advisor#19]
If I load any courses show page, I get the following 2 routing errors:
1. No route matches [GET] "/courses/js/scripts.js"
2. No route matches [GET] "/courses/assets/koyuturk.jpg"

**Comment by Aaronneyer** [comment]
Ya, looks like that's a relic of a few things that got moved over from the
Bootply. I'll put together a commit soon to do a big old clean up of the
HTML there.
