### ISSUE TITLE
Scrape rake task is no longer building. 

### ISSUE THREAD

**Issue by StephHippo** [Aaronneyer/the_jolly_advisor#24]
No idea what's up. Looking into it now so I can kick this off before bed.

Something about insecure world writable.

**Comment by StephHippo** [comment]
This was literally just a whitespace problem with me typing it in. Please forgive. 

Don't open issues after experimenting with SEPIA, kids. Known to cause widespread anger, frustration, and mistakes.

**Comment by Aaronneyer** [comment]
Oh ya, Rake is weird. I had the same problem, it took me a while to realize why it wouldn't work when I was testing out rake tasks with arguments.
